[versions]
agp = "8.5.1"
firebaseBom = "33.1.2"
appcompat = "1.7.0"
googleServices = "4.4.2"
gradle = "7.0.4"
material = "1.12.0"
activity = "1.9.1"
constraintlayout = "2.1.4"
firebaseAuth = "23.0.0"
firebaseFirestore = "25.0.0"
googleGmsGoogleServices = "4.4.2"

[libraries]
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
google-services = { module = "com.google.gms:google-services", version.ref = "googleServices" }
gradle = { module = "com.android.tools.build:gradle", version.ref = "gradle" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
firebase-auth = { group = "com.google.firebase", name = "firebase-auth", version.ref = "firebaseAuth" }
firebase-firestore = { group = "com.google.firebase", name = "firebase-firestore", version.ref = "firebaseFirestore" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
google-gms-google-services = { id = "com.google.gms.google-services", version.ref = "googleGmsGoogleServices" }

